- name: copying dummyservice template
  template:
    src: systemd/dummyservice.j2
    dest: /etc/systemd/system/dummyservice.service
    mode: 0644
  tags: dummyservice

- name: enabling dummyservice
  systemd:
    name: dummyservice
    state: started
    enabled: yes
    daemon_reload: yes
